version: '2.1'

services:
    php:
        build: docker/php7-fpm-debian
        environment:
             FPM_UID: ${UID:-1000}
             FPM_GID: ${GID:-1000}
        volumes:
            - .:/var/www/html
            - ${HOMEDIR}:/var/www/home
    nginx:
        build: docker/nginx
        links:
            - php
        volumes_from:
            - php
        environment:
             VIRTUAL_HOST: ${VIRTUAL_HOST}
             LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
             LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
    default:
        external:
            name: ${PROXY_NETWORK}

