version: '2.1'

services:
    php:
        image: kilik/php:7.1-stretch-dev
        environment:
             FPM_UID: ${UID:-1000}
             FPM_GID: ${GID:-1000}
        volumes:
            - .:/var/www/html
            - ${HOME}:/var/www/home
    nginx:
        image: kilik/nginx:symfony-3.x-stretch
        links:
            - php
        volumes_from:
            - php
        environment:
             VIRTUAL_HOST: ${VIRTUAL_HOST}
             LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
             LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
    default:
        external:
            name: ${PROXY_NETWORK}

