guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true

    clients:
        reqres:
            base_url: "https://reqres.in/"
            options:
                headers:
                    Accept: "application/json"
                timeout: 30
